---
- name: Generate kickstart configuration from template for each host
  ansible.builtin.template:
    src: ../template/ks.cfg.j2
    dest: "{{ local_workspace }}/ks-{{ hostvars[item].host.hostname }}.cfg"
    mode: '0644'
  vars:
    host: "{{ hostvars[item].host }}"
    ansible_host: "{{ hostvars[item].ansible_host }}"
    idrac_user: "{{ hostvars[item].idrac_user }}"
    idrac_password: "{{ hostvars[item].idrac_password }}"

- name: Create empty 10MB image file for Kickstart for each host
  ansible.builtin.command: dd if=/dev/zero of={{ local_workspace }}/{{ hostvars[item].host.hostname }}-{{ img_filename }} bs=1M count=10
  changed_when: true

- name: Format the local image file as FAT32 with label OEMDRV for each host
  ansible.builtin.command: mkfs.vfat -F 32 -n OEMDRV {{ local_workspace }}/{{ hostvars[item].host.hostname }}-{{ img_filename }}
  changed_when: true

- name: Copy ks.cfg into the local FAT32 image using mcopy for each host
  ansible.builtin.command: mcopy -i {{ local_workspace }}/{{ hostvars[item].host.hostname }}-{{ img_filename }} {{ local_workspace }}/ks-{{ hostvars[item].host.hostname }}.cfg ::/ks.cfg
  changed_when: true
...