---
# Kickstart Preparation Variables
local_iso_path: "/path/to/iso-dir" # directory where ISOs are located on controller
iso_filename: "rhel-9.7-x86_64-dvd.iso"
liveiso_filename: "CentOS-Stream-MIN-Live-Automation.x86_64-10.iso" # Live ISO for bare metal operations (introspection, storage wipe, etc.)
img_filename: "oemdrv.img"
local_workspace: "/tmp/kickstart"

# HTTP Server Configuration
http_server_base_url: "http://provisioner.domain.test/provision"
remote_http_docroot: "/var/www/html/provision"
...