collections:
  - name: community.general
    version: ">=7.0"
  - name: ansible.posix
  - name: redhat.satellite
  - name: infra.ah_configuration
  - name: infra.leapp
  - name: infra.lvm_snapshots
  - name: infra.convert2rhel
  - name: infra.eda_configuration
  - name: infra.ee_utilities
  - name: infra.osbuild
