- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: mini_rhis_installer
      vars:
        rhis_container_name: "rhis-provisioner"
        demo_admin_password: "bj8H7ndC7$"
