- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: minirhis_installer
      vars:
        rhis_container_name: "minirhis-provisioner"
        demo_admin_password: "bj8H7ndC7$"
